# Generated by Django 5.2.11 on 2026-03-27 04:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Created Reminder'), ('edit', 'Edited Reminder'), ('delete', 'Deleted Reminder'), ('pause', 'Paused Reminder'), ('resume', 'Resumed Reminder'), ('email_sent', 'Email Sent'), ('admin_create_user', 'Admin Created User'), ('admin_create_category', 'Admin Created Category')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('title', models.CharField(default='Untitled Reminder', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('email_to', models.EmailField(default='example@email.com', max_length=254)),
                ('email_cc', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('next_trigger', models.DateTimeField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.IntegerField(default=1)),
                ('daily_mode', models.CharField(blank=True, max_length=20)),
                ('hour_interval', models.IntegerField(blank=True, null=True)),
                ('by_weekday', models.CharField(blank=True, max_length=50)),
                ('monthly_mode', models.CharField(blank=True, max_length=20)),
                ('by_monthday', models.IntegerField(blank=True, null=True)),
                ('by_setpos', models.IntegerField(blank=True, null=True)),
                ('yearly_mode', models.CharField(blank=True, max_length=20)),
                ('by_month', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('occurrence_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='reminder_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
