# Generated by Django 5.2.11 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0002_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['next_trigger']},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Created Reminder'), ('edit', 'Edited Reminder'), ('delete', 'Deleted Reminder'), ('pause', 'Paused Reminder'), ('resume', 'Resumed Reminder'), ('email_sent', 'Email Sent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_to',
            field=models.TextField(default='example@email.com'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='next_trigger',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed')], default='active', max_length=20),
        ),
    ]
