# Generated by Django 5.2.11 on 2026-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0003_alter_reminder_options_activitylog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
    ]
