# Generated by Django 5.2.11 on 2026-03-29 06:16

import django.utils.timezone
import reminder_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0004_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='range_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Created Reminder'), ('edit', 'Edited Reminder'), ('delete', 'Deleted Reminder'), ('pause', 'Paused Reminder'), ('resume', 'Resumed Reminder'), ('email_sent', 'Email Sent'), ('create_user', 'Created User'), ('edit_user', 'Edited User'), ('delete_user', 'Deleted User')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_to',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=reminder_app.models._default_time),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
