# Generated by Django 5.2.11 on 2026-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0005_reminder_range_type_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
