# Generated by Django 5.2.11 on 2026-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0006_reminder_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
