# Generated by Django 5.2.11 on 2026-03-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0007_reminder_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this FAQ from the website without deleting it.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first (e.g., 1 goes above 2).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
