# Generated by Django 5.2.11 on 2026-04-06 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0008_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='by_weekday',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='daily_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_cc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='monthly_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='yearly_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'next_trigger'], name='reminder_ap_status_8ed919_idx'),
        ),
    ]
