# Generated by Django 5.2.11 on 2026-04-06 09:42

import django.db.models.deletion
import reminder_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0009_alter_faq_options_alter_reminder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=reminder_app.models.reminder_directory_path),
        ),
    ]
