# Generated by Django 5.2.11 on 2026-04-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0010_alter_activitylog_user_alter_reminder_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information / Activity'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='path',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
