"""
Django settings for reminder_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ohpu*qznw_b%_qaw8r!)mmvcuaqgvjy6=+ap3%6%ug-c2la090'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reminder_app.apps.ReminderAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reminder_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'reminder_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'ReminderDB',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost\\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=yes;TrustServerCertificate=yes;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'sujal7k7@gmail.com'
EMAIL_HOST_PASSWORD = 'dxczgpahfrmcholj'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


import os
from datetime import datetime

# Log directories
LOG_DIR = os.path.join(BASE_DIR, "logs")
ACTIVITY_LOG_DIR = os.path.join(LOG_DIR, "activity")
ERROR_LOG_DIR = os.path.join(LOG_DIR, "errors")

os.makedirs(ACTIVITY_LOG_DIR, exist_ok=True)
os.makedirs(ERROR_LOG_DIR, exist_ok=True)

# Current date
TODAY = datetime.now().strftime("%Y-%m-%d")

ACTIVITY_LOG_FILE = os.path.join(ACTIVITY_LOG_DIR, f"activity-{TODAY}.log")
ERROR_LOG_FILE = os.path.join(ERROR_LOG_DIR, f"errors-{TODAY}.log")


LOGGING = {

    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "{asctime} | {levelname} | {name} | {message}",
            "style": "{",
        },
    },

    "handlers": {

        "activity_file": {
            "class": "logging.FileHandler",
            "filename": ACTIVITY_LOG_FILE,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": "INFO",
        },

        "error_file": {
            "class": "logging.FileHandler",
            "filename": ERROR_LOG_FILE,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": "WARNING",  # FIX: Capture WARNING too, not just ERROR
        },

        # FIX: Added console handler for development visibility
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": "DEBUG",
        },

    },

    "loggers": {

        "activity_logger": {
            "handlers": ["activity_file", "console"],  # FIX: Added console
            "level": "INFO",
            "propagate": False,
        },

        "error_logger": {
            "handlers": ["error_file", "console"],  # FIX: Added console
            "level": "WARNING",  # FIX: Capture WARNING too
            "propagate": False,
        },

        "django": {
            "handlers": ["error_file", "console"],
            "level": "WARNING",  # FIX: Capture WARNING too
            "propagate": False,  # FIX: Was True — caused every error to be logged TWICE
                                 # (once by "django" logger, once by root "" logger)
        },

        # FIX: Root logger now only handles truly unexpected loggers.
        # Removed error_file handler here to prevent duplicate entries.
        # Django errors are handled by the "django" logger above.
        "": {
            "handlers": ["console"],
            "level": "WARNING",
        },

    },
}


# =========================================================
# MEDIA FILES (Uploaded Attachments)
# =========================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')